---

version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.3

    steps:
      - checkout
      - run:
          name: Download data files
          command: |
            python3 scripts/pulldata.py
            python3 -m zipfile -c datapackage.zip datapackage.json data

      - store_artifacts:
          path: datapackage.zip
          destination: datapackage.zip
      - store_artifacts:
          path: datapackage-digest.json
          destination: datapackage-digest.json
